name: "CI"

on: [push]
jobs:
  Mac_OS_X_No_Boost:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required packages
        run: |
          brew install ninja cmake ccache libxml2
      - name: Get timestamp
        id: time
        run: python3 -c "from datetime import datetime; print('time='+datetime.now().strftime('%Y-%m-%d-%H-%M-%S'))" >> $GITHUB_ENV
      - name: Restore ccache
        id: ccache
        uses: actions/cache@v3
        with:
          path: .ccache
          key: osx_brew_nob_-ci-${{env.time}}
          restore-keys: osx_brew_nob_-ci-
      - name: Setup ccache
        run: |
          export PATH=/usr/local/bin:$PATH #:/usr/local/opt/qt/bin
          ccache --set-config=cache_dir="$GITHUB_WORKSPACE/.ccache"
          ccache --set-config=max_size=400M
          ccache --set-config=compression=true
          ccache -z
      - name: Configure CMake
        run: |
          export PATH=/usr/local/bin:$PATH #:/usr/local/opt/qt/bin
          ./ns3 configure -d optimized --enable-asserts --enable-examples --enable-tests -G"Ninja"
      - name: Build ns-3
        run: |
          export PATH="$PATH" #:/usr/local/opt/qt/bin
          ./ns3 build
      - name: Print ccache statistics
        id: ccache_results
        run: |
          ccache -s
          python3 -c "import re, subprocess;print('cache_misses=%d' % int(re.findall('cache_miss(.*)', subprocess.check_output(['ccache', '--print-stats']).decode())[0]))" >> $GITHUB_ENV
      - name: Run tests and examples
        if: env.cache_misses != '0'
        run: ./test.py --no-build
  
  Mac_OS_X_Boost:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required packages
        run: |
          brew install ninja cmake ccache libxml2 boost
      - name: Get timestamp
        id: time
        run: python3 -c "from datetime import datetime; print('time='+datetime.now().strftime('%Y-%m-%d-%H-%M-%S'))" >> $GITHUB_ENV
      - name: Restore ccache
        id: ccache
        uses: actions/cache@v3
        with:
          path: .ccache
          key: osx_brew_b_-ci-${{env.time}}
          restore-keys: osx_brew_b_-ci-
      - name: Setup ccache
        run: |
          export PATH=/usr/local/bin:$PATH #:/usr/local/opt/qt/bin
          ccache --set-config=cache_dir="$GITHUB_WORKSPACE/.ccache"
          ccache --set-config=max_size=400M
          ccache --set-config=compression=true
          ccache -z
      - name: Configure CMake
        run: |
          export PATH=/usr/local/bin:$PATH #:/usr/local/opt/qt/bin
          ./ns3 configure -d optimized --enable-asserts --enable-examples --enable-tests -G"Ninja"
      - name: Build ns-3
        run: |
          export PATH="$PATH" #:/usr/local/opt/qt/bin
          ./ns3 build
      - name: Print ccache statistics
        id: ccache_results
        run: |
          ccache -s
          python3 -c "import re, subprocess;print('cache_misses=%d' % int(re.findall('cache_miss(.*)', subprocess.check_output(['ccache', '--print-stats']).decode())[0]))" >> $GITHUB_ENV
      - name: Run tests and examples
        if: env.cache_misses != '0'
        run: ./test.py --no-build  

